#pragma once

#define OLED_TIMEOUT 60000
#define OLED_BRIGHTNESS 120

#define TAPPING_TERM 225

#define SPLIT_WPM_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
