#pragma once

#define OLED_TIMEOUT 30000
#define OLED_BRIGHTNESS 80
#define OLED_DISABLE_WHEN_USB_SUSPENDED

#define TAPPING_TERM 225

#define SPLIT_WPM_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
